### ISSUE TITLE
关于前台文章css显示的问题

### ISSUE THREAD

**Issue by crazyming9528** [LuRenJiasWorld/WP-Editor.md#395]
我有看到后台编辑文章页面会加载这个css:  assets/Editormd/editormd.min.css

但是在文章前台我没有找到这个css文件,这导致了文章显示效果和  后台编辑时产生的预览 效果不一致.

我想问一下 如果要一致,我是要在主题文件中手动引入这个css ,然后在文章包裹层加入 .markdown-body 这个class吗?

还是后台有开关之类的(ps:我真没找到)

**Comment by LuRenJiasWorld** [comment]
你好，目前前台CSS样式由主题决定。这个是所有WordPress第三方编辑器的通病。

后续计划加入覆盖主题CSS样式的选项，但一方面存在潜在兼容性问题，另一方面不知道是否所有用户都需要这个功能，因此优先级暂时不是很高，如果要做的话可能得放到明年。

抱歉带来不便。

**Comment by LuRenJiasWorld** [comment]
> 我想问一下 如果要一致,我是要在主题文件中手动引入这个css ,然后在文章包裹层加入 .markdown-body 这个class吗?

你可以先尝试一下，理论上可行，但editormd.min.css体积控制可能不太理想，会造成前台页面加载速度变慢。如果成功或有其他好的建议欢迎反馈提供思路。

举例：本插件的表格样式在不同主题下表现各异。我个人的解决方法是直接配置当前主题的自定义css样式（如果需要修改的地方比较多还可以使用子主题），参考代码如下：
```css
table {
    left: 0;
    right: 0;
    margin: 20px auto;
    padding: 15px 30px;
    border-spacing: 0px;
}

tr, td, th {
	border-top: 1px solid #d3d3d3;
	padding: 8px 12px;
	text-align: center;
}

tr:nth-child(even), th {
	background-color: #f3f3f3;
}

tbody > tr:hover {
	background-color: #d2d2d2;
	color: white;
}
```

使用该方法修改后的表格样式参考[本链接](https://untitled.pw/repairing/1554.html)

我依旧会尽快跟进相关功能的更新，但需要一点时间，请耐心等待。
