### ISSUE TITLE
代码行号显示与代码行实际位置有出入

### ISSUE THREAD

**Issue by laitianliu** [LuRenJiasWorld/WP-Editor.md#397]
在插件的语法高亮设置如下：
![image](https://user-images.githubusercontent.com/24669671/71303786-9bbdf300-23f8-11ea-8569-ad916b5faca2.png)
在文章页面代码块显示效果如下：
![image](https://user-images.githubusercontent.com/24669671/71303810-d9bb1700-23f8-11ea-9c0d-4fff0c0729d0.png)

把主题风格换为默认后，文章代码块显示效果如下：
![image](https://user-images.githubusercontent.com/24669671/71303838-20a90c80-23f9-11ea-9551-fe1b6d598aa3.png)

还有就是markdown编辑器预览界面与实际发布后的效果不一致是属于正常吗？感谢作者的辛劳付出！

**Comment by LuRenJiasWorld** [comment]
你好，我猜测问题应该是你主题的字体与代码高亮部分的字体冲突了，但需要进一步确认，可以给出相应的博文链接吗，这样我排查起来会更容易？

附链接：[https://untitled.pw/software/1346.html](https://untitled.pw/software/1346.html)，默认情况下的行数显示是正常的。

**Comment by laitianliu** [comment]
这是我测试web端的页面，也有可能是主题默认的css格式跟现在的css混合冲突了。有这种可能吗？我发现有一个主题是正常的。coy主题，但是觉得怪怪的。
![image](https://user-images.githubusercontent.com/24669671/71332275-87046b00-2570-11ea-86c9-2672be2cf274.png)
@LuRenJiasWorld 
链接地址是：http://47.107.84.48/wordpress/?p=125

**Comment by LuRenJiasWorld** [comment]
<img width="1919" alt="QQ20191223-153416@2x" src="https://user-images.githubusercontent.com/29622423/71343089-b380ad00-2599-11ea-8699-50579113022a.png">
已为你标出问题所在CSS配置，与猜测一致，是主题与插件冲突导致的，请根据你的情况自行决定如何处理。我的建议是在主题的自定义部分设置以下CSS：

```css
pre[class*="language-"].line-numbers {
    font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace;
    font-size: 1em;
}
```

你可以尝试一下，然后看看是否解决你的问题。
