### ISSUE TITLE
markdown代码块高亮问题

### ISSUE THREAD

**Issue by huahuayu** [LuRenJiasWorld/WP-Editor.md#442]
## 问题描述
有一些代码块是日志、配置或者是一段text，不需要高亮展示的，但是还是会被高亮展示

而且我都标注了是text，为什么还要提取关键字来highlight呢  

比如下面是一个报错信息，不属于任何编程语言的，高亮的依据不知道是什么  
![image](https://user-images.githubusercontent.com/1725060/78110322-52386780-742d-11ea-8dcd-bf375aea5efb.png)

**Comment by LuRenJiasWorld** [comment]
这种的话，可以无需指定语言。直接使用三个反引号包裹起来即可。

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/78110888-56b15000-742e-11ea-9482-25693a719383.png)
如图所示

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/78110904-629d1200-742e-11ea-9e9c-b460b0a3b15e.png)

**Comment by huahuayu** [comment]
展示效果一样，我试过了
https://liushiming.cn/2020/02/26/java-classpathresource-filenotfoundexception/

你光写数字当然没问题，试下下面这段

```
java.io.FileNotFoundException: class path resource [foo.txt] cannot be opened because it does not exist
```

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/78111104-c1fb2200-742e-11ea-9b4c-d57b524c5485.png)

似乎是主题或第三方插件引入的代码高亮？因为Prism.js引入的代码高亮会携带`language-xxx`的class，但这个没有。

还是建议检查一下和主题/第三方插件的兼容性问题先😅。

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/78111312-10102580-742f-11ea-8079-76ddb4f77e0d.png)

我这边还是没能复现。

**Comment by huahuayu** [comment]
我做了两件事：
1. disable所有插件，只留下了wp-editor.md
2. inspect一个text文本的高亮
![image](https://user-images.githubusercontent.com/1725060/78111892-f28f8b80-742f-11ea-9c76-31db4d865441.png)

我看到有language-text的class啊  

https://liushiming.cn/2020/02/25/java-inner-class/

**Comment by LuRenJiasWorld** [comment]
> 我做了两件事：
> 
> 1. disable所有插件，只留下了wp-editor.md
> 2. inspect一个text文本的高亮
>    ![image](https://user-images.githubusercontent.com/1725060/78111892-f28f8b80-742f-11ea-9c76-31db4d865441.png)
> 
> 我看到有language-text的class啊

不使用text呢？只使用三个反引号试试看，因为Prism.js并没有名为Text的语法高亮规则。

prettyprint有可能是主题引入的，因为之前的一个Issue也有用户提到过类似的问题，分析了很久发现是主题自带了代码高亮。

**Comment by LuRenJiasWorld** [comment]
你可以查看一下这个页面的源码，会发现源码里只有language-text（虽然不是正确用法但是没关系）。

但是加载之后，就会多出来一个prettyprint的class。

然后如果你用审查元素手动去除prettyprint，错误的高亮就消失了。

![image](https://user-images.githubusercontent.com/29622423/78112359-b4469c00-7430-11ea-82d0-978d4e0c948d.png)

进一步分析，prettyprint的样式的确是来自主题。你可以修改一下这个主题，去掉相应的CSS源码，也许可以解决这个问题。

**Comment by huahuayu** [comment]
我把text去掉了，效果一样  

所以你怀疑是主题自带的高亮？能不能在我刚刚给的链接上confirm一下？

我不会前端，如果是主题自带的，怎么disable主题的用wp-editor.md的呢

**Comment by LuRenJiasWorld** [comment]
> 我把text去掉了，效果一样
> 
> 所以你怀疑是主题自带的高亮？能不能在我刚刚给的链接上confirm一下？
> 
> 我不会前端，如果是主题自带的，怎么disable主题的用wp-editor.md的呢

你可以修改一下这个主题，去掉相应的CSS源码。也就是包含`.prettyprint`的部分。

**Comment by huahuayu** [comment]
好的，我试下看，回头跟你说效果

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/78112538-efe16600-7430-11ea-89f9-5878931b0cff.png)

这一部分在你主题CSS源码的最后面，可以不急着删除，先用`/* */`注释掉。

**Comment by LuRenJiasWorld** [comment]
> 好的，我试下看，回头跟你说效果

好的。

**Comment by huahuayu** [comment]
我在后台->外观->编辑主题里看到有这么多css，到底是哪一个，是不是就在这里改的？
![image](https://user-images.githubusercontent.com/1725060/78112977-975e9880-7431-11ea-91eb-a8c6e9703ce5.png)

**Comment by LuRenJiasWorld** [comment]
是的，修改main.css，注释掉最后面一段包含`.prettyprint`的CSS样式。

**Comment by huahuayu** [comment]
我直接到服务器vi main.css注释掉了
``` css
.prettyprint,
pre.prettyprint {
    background-color: #272822;
    border: none;
    overflow: auto;
    padding: 10px 15px;
    max-height: 637px;
}
.prettyprint.linenums,
pre.prettyprint.linenums {
    -webkit-box-shadow: inset 40px 0 0 #39382E, inset 41px 0 0 #464741;
    -moz-box-shadow: inset 40px 0 0 #39382E, inset 41px 0 0 #464741;
    box-shadow: inset 40px 0 0 #39382E, inset 41px 0 0 #464741;
}
.prettyprint.linenums ol,
pre.prettyprint.linenums ol {
    margin: 0 0 0 30px;
}
.prettyprint.linenums ol li,
pre.prettyprint.linenums ol li {
    padding-left: 12px;
    color: #bebec5;
    line-height: 20px;
    margin-left: 0;
    list-style: decimal;
    margin-bottom: 0;
}

.prettyprint .com { color: #93a1a1; }
.prettyprint .lit { color: #AE81FF; }
.prettyprint .pun,
.prettyprint .opn,
.prettyprint .clo { color: #F8F8F2; }
.prettyprint .fun { color: #dc322f; }
.prettyprint .str,
.prettyprint .atv { color: #E6DB74; }
.prettyprint .kwd,
.prettyprint .tag { color: #F92659; }
.prettyprint .typ,
.prettyprint .atn,
.prettyprint .dec,
.prettyprint .var { color: #A6E22E; }
.prettyprint .pln { color: #66D9EF; }
```

有效果

现在text是显示这样 
![image](https://user-images.githubusercontent.com/1725060/78113717-b6115f00-7432-11ea-8eb7-3b9b531e9434.png)

不写text是这样
![image](https://user-images.githubusercontent.com/1725060/78113804-de00c280-7432-11ea-927f-b869d3a770cc.png)

说明还是识别text的
