### ISSUE TITLE
行内代码tag和katex嵌套无法正常显示

### ISSUE THREAD

**Issue by lllhys** [LuRenJiasWorld/WP-Editor.md#470]
行内代码tag和katex嵌套时无法正常显示
![image](https://user-images.githubusercontent.com/37238105/84386100-55b54f80-ac23-11ea-89eb-48f27aa4a10b.png)

**Comment by LuRenJiasWorld** [comment]
你好，行内代码的设计原则就是『原文输出』，不支持LaTeX渲染。但你可以通过WordPress自定义CSS的方式给LaTeX加一个类似外观的外框/背景。

这里我可以提供一个示例CSS供你参考：

```css
span.katex.inline {
    background-color: #E4E4E4;
    padding: 2px 4px;
    border-radius: 4px;
    margin: 0 4px;
}
```

效果如图所示：

![image](https://user-images.githubusercontent.com/29622423/84402422-f95c2b00-ac36-11ea-9972-41ebfb206025.png)
