### ISSUE TITLE
关于前端不能显示$符号

### ISSUE THREAD

**Issue by starzyn** [LuRenJiasWorld/WP-Editor.md#471]
你好，在使用插件之后，在代码块中定义使用xml语法时，后台编辑过程中的显示是正常的，但是在前台显示的时候就会丢失‘$’符号

**Comment by LuRenJiasWorld** [comment]
你好，请问可以提供一个可以复现故障的文章链接吗？

**Comment by starzyn** [comment]
http://www.starblog.site/starblog/index.php/2020/06/10/ssm-integrated/
这个是前台效果，问题出在第二个代码块的第16-20行，后台确实是有$符号的，而前台是看不到的

**Comment by LuRenJiasWorld** [comment]
好的，明白了。这是一个已知的BUG，表现为`<pre>`标签里的内容会被当做正文被解析。

我将会在月底发布的10.2.0版本修复这一问题，到时候会通知你更新文章（在编辑页面重新保存一次即可实现文章更新），目前没有临时的解决方法。

非常抱歉带来不便。

**Comment by LuRenJiasWorld** [comment]
此外，我留意到你的代码高亮样式存在美观上的问题（比如没有和行号对齐），这是因为主题自带了部分代码高亮样式，和本插件产生冲突导致的。我正在想办法解决这一问题，目前你可以使用WordPress的自定义CSS方式临时解决。我提供一个示例供你参考：

```css
pre[class*="language-"] {
    font-family: monospace !important;
}

code[class*="language-"] {
    padding: 0 !important;
    margin: 0 !important;
}

pre[class*="language-"].line-numbers {
    padding-left: 5em !important;
}
```

效果如图所示：

![image](https://user-images.githubusercontent.com/29622423/84559538-1c3d2b00-ad6e-11ea-92a8-ffe82b86398f.png)


另外，Java下的properties文件其实就是ini文件，你可以使用ini的高亮样式对其进行高亮，如下图所示：

![image](https://user-images.githubusercontent.com/29622423/84559569-45f65200-ad6e-11ea-9122-64ba97c9d407.png)
