### ISSUE TITLE
关于公式大小的问题

### ISSUE THREAD

**Issue by RichardZhang2019** [LuRenJiasWorld/WP-Editor.md#486]
您好，WP-Editor.md插件非常好用，但在使用中发现几个问题，请您帮忙看一下。

- 公式比周围字体高出很多，看起来很突兀，是否可以调整小一点，或者是否有开关配置？
- 图片变小了很多，是主题的问题？还是插件的问题？也无法居中显示。
- 前台评论如果开启支持markdown语法，则一直显示加载状态，不知道什么原因。

多谢！我的网址如下
https://www.zcr.cool/2020/09/wp-editor/

**Comment by LuRenJiasWorld** [comment]
感谢对本插件的支持，你提供的地址非常有帮助，以下是针对这三个问题的解答：

1. 公式默认是比字体略大一点的，如果不喜欢可以通过CSS调节，目前没有设置开关的计划，但后续会在设置中增加一个自定义CSS样式/CSS样式模板的功能。

解决问题1的CSS如下，你可以在WordPress自定义主题的地方设定CSS：

```css
.katex {
    line-height: 1em !important;
    font-size: 1em !important;
}
```

2. 图片居中显示&大小是主题导致的，本插件暂时不会对样式进行任何处理，你也可以通过CSS解决这一问题：

```css
.entry .entry-content img, .entry .entry-content video {
    max-width: 100% !important;
    vertical-align: top !important;
    width: 600px !important;
    margin: 0 auto !important;
    display: block !important;
    zoom: 100% !important;
}
```

3. 前台评论开启Markdown报错是因为与思维导图功能冲突导致，你可以先关闭思维导图看看问题是否依旧存在。该问题会在未来版本予以解决。

感谢支持。
