### ISSUE TITLE
[Feature]可否添加一个选择是否自动为Markdown标题添加多级编号的选项

### ISSUE THREAD

**Issue by shengqiangzhang** [LuRenJiasWorld/WP-Editor.md#525]
**该功能的缺失是否引起你的使用不便？ | Is your feature request related to a problem?**
我在使用Markdown编辑的时候，想为标题自动添加编号，但是默认的效果是没有添加编号的，所以我在`.md`文件里面添加了`css`来自动添加编号。

但是在正式发布文章的时候，发现这部分的`css`会影响到主页的东西。主页中的非文章区域的部分，只要是一级标题、二级标题、……都会自动编号，这不是我预期想要的效果。

**你认为该功能应该是什么样的？ | Describe the solution you'd like**
`css`部分只对文章内的标题生效，而不对主页中的其他元素生效。

**其他信息 | Additional context**

我目前的做法是这样的：

1. 在创建文章中，直接插入`css`部分
```css
<style type="text/css">
    h1 { counter-reset: h2counter; }
    h2 { counter-reset: h3counter; }
    h3 { counter-reset: h4counter; }
    h4 { counter-reset: h5counter; }
    h5 { counter-reset: h6counter; }
    h6 { }
    h2:before {
      counter-increment: h2counter;
      content: counter(h2counter) ".\0000a0\0000a0";
    }
    h3:before {
      counter-increment: h3counter;
      content: counter(h2counter) "."
                counter(h3counter) ".\0000a0\0000a0";
    }
    h4:before {
      counter-increment: h4counter;
      content: counter(h2counter) "."
                counter(h3counter) "."
                counter(h4counter) ".\0000a0\0000a0";
    }
    h5:before {
      counter-increment: h5counter;
      content: counter(h2counter) "."
                counter(h3counter) "."
                counter(h4counter) "."
                counter(h5counter) ".\0000a0\0000a0";
    }
    h6:before {
      counter-increment: h6counter;
      content: counter(h2counter) "."
                counter(h3counter) "."
                counter(h4counter) "."
                counter(h5counter) "."
                counter(h6counter) ".\0000a0\0000a0";
    }
</style>
```

2. 发布文章

3. 文章内显示正常，但是在主页中，其他区域的标题也会给自动添加编号了。

![image](https://user-images.githubusercontent.com/28225826/108617592-b2c00100-7452-11eb-9b6d-ef18c2f7514d.png)
