### ISSUE TITLE
[BUG]贴Latex代码的时候报错

### ISSUE THREAD

**Issue by dryangyq** [LuRenJiasWorld/WP-Editor.md#578]
**BUG描述 | Describe the bug**
> 为了显示公式，我开启了KaTex功能，但是这样我在文章中贴代码的时候，前段就报错了。

```
```latex
\begin{document}
```

前端错误：
ParseError: KaTeX parse error: No such environment: document at position 7: \begin{̲d̲o̲c̲u̲m̲e̲n̲t̲}̲

**Comment by LuRenJiasWorld** [comment]
你好，本插件接入的 KaTeX 只支持有限的 LaTeX 语法：https://katex.org/

**Comment by dryangyq** [comment]
> 你好，本插件接入的 KaTeX 只支持有限的 LaTeX 语法：https://katex.org/

不是，我的本意是要贴latex的代码，不是要让KaTex去执行这个代码。有什么办法吗？

**Comment by LuRenJiasWorld** [comment]
> > 你好，本插件接入的 KaTeX 只支持有限的 LaTeX 语法：https://katex.org/
> 
> 不是，我的本意是要贴latex的代码，不是要让KaTex去执行这个代码。有什么办法吗？

了解了，暂时没有很好的办法，后面我新增一个 `latex-code` 的语言类型，用于和 LaTeX 公式区分开来。
有一个 Hack 的解决方案，开启 HTML 解析后，使用如下 HTML 代码来插入 LaTeX 类型的代码高亮：
```html
<pre class=" line-numbers language-latex"><code class="  language-latex">\begin{document}</code></pre>
```

**Comment by dryangyq** [comment]
> > > 你好，本插件接入的 KaTeX 只支持有限的 LaTeX 语法：https://katex.org/
> > 
> > 
> > 不是，我的本意是要贴latex的代码，不是要让KaTex去执行这个代码。有什么办法吗？
> 
> 了解了，暂时没有很好的办法，后面我新增一个 `latex-code` 的语言类型，用于和 LaTeX 公式区分开来。 有一个 Hack 的解决方案，开启 HTML 解析后，使用如下 HTML 代码来插入 LaTeX 类型的代码高亮：
> 
> ```
> <pre class=" line-numbers language-latex"><code class="  language-latex">\begin{document}</code></pre>
> ```

好的，感谢。
另外，支持的代码里面，我看没有text啊，就是纯文本的，有时候会贴一些错误日志什么的，感觉用纯文本会好一点。

**Comment by LuRenJiasWorld** [comment]
> > > > 你好，本插件接入的 KaTeX 只支持有限的 LaTeX 语法：https://katex.org/
> > > 
> > > 
> > > 不是，我的本意是要贴latex的代码，不是要让KaTex去执行这个代码。有什么办法吗？
> > 
> > 
> > 了解了，暂时没有很好的办法，后面我新增一个 `latex-code` 的语言类型，用于和 LaTeX 公式区分开来。 有一个 Hack 的解决方案，开启 HTML 解析后，使用如下 HTML 代码来插入 LaTeX 类型的代码高亮：
> > ```
> > <pre class=" line-numbers language-latex"><code class="  language-latex">\begin{document}</code></pre>
> > ```
> 
> 好的，感谢。 另外，支持的代码里面，我看没有text啊，就是纯文本的，有时候会贴一些错误日志什么的，感觉用纯文本会好一点。

可以直接不提供语言类型，如：
![image](https://user-images.githubusercontent.com/29622423/224229941-5e4394ed-0fb2-41f5-b85c-9ec152d1136c.png)
看看这样能否满足纯文本粘贴的需求。

**Comment by dryangyq** [comment]
> 

不行，好像code不带class之后，就没有样式了。跟空白文本没区别。
![image](https://user-images.githubusercontent.com/67722197/224230998-7994e2ee-05c1-42dd-b73c-def7b3b5b23e.png)

**Comment by LuRenJiasWorld** [comment]
> > 
> 
> 不行，好像code不带class之后，就没有样式了。跟空白文本没区别。 ![image](https://user-images.githubusercontent.com/67722197/224230998-7994e2ee-05c1-42dd-b73c-def7b3b5b23e.png)

这个是因为你的主题没有带纯 pre 标签的样式，可以在 CodePen 等网站搜索 CSS Code block 等关键词，找一下相关的样式对其进行美化。

**Comment by LuRenJiasWorld** [comment]
最简单的样式（可以粘到自定义CSS里试一下）：
```css
code {
    padding: 2px 4px;
}

pre, code {
    background: #f8f8f8;
    font-family: Menlo, Monaco, Consolas, "Lucida Console", "Courier New", monospace;
    font-size: .92857em;
}

pre {
    margin: 2em 0;
    overflow: auto;
    background: none;
    border: 1px solid #ddd;
}

pre code {
    padding: 0;
    display: block;
}
```
